In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("a/Inm Estadisticas_csv.csv",delimiter=";")
df.head(1)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 3: invalid continuation byte

In [3]:
df.columns

Index(['OBJECTID *', 'Join_Count', 'TARGET_FID', 'Join_Count.1',
       'TARGET_FID.1', 'F1', 'id', 'sq_mt_built', 'n_rooms', 'n_bathrooms',
       'floor', 'buy_price', 'buy_price_by_area', 'is_renewal_needed',
       'is_new_development', 'has_lift', 'is_exterior', 'has_parking', 'lat',
       'long', 'OBJECTID', 'geodb_oid', 'CODDIS', 'NOMDIS', 'CODBAR',
       'CODDISTRIT', 'CODBARRIO', 'NOMBRE', 'ORIG_FID', 'OBJECTID.1',
       'Pol Local', 'Supermerca', 'PoliciaNac', 'Bomberos', 'AutobusesU',
       'Bocas de m', 'Farmacias', 'Hospitales', 'CentrosSal', 'CentrosEns',
       'ColegiosPu'],
      dtype='object')

In [5]:
df["security"] = df.loc[:,["Pol Local",'PoliciaNac','Bomberos']].sum(axis=1)
df["transport"] = df.loc[:,["Bocas de m",'AutobusesU']].sum(axis=1)
df["health"] = df.loc[:,["Farmacias",'Hospitales','CentrosSal']].sum(axis=1)
df["education"] = df.loc[:,["CentrosEns",'ColegiosPu']].sum(axis=1)

In [6]:
df = df.drop(columns=['OBJECTID *', 'Join_Count', 'TARGET_FID', 'Join_Count.1',
       'TARGET_FID.1', 'F1', 'OBJECTID', 'geodb_oid', 'CODDIS', 'NOMDIS', 'CODBAR',
       'NOMBRE', 'ORIG_FID', 'OBJECTID.1','Pol Local', 'Supermerca', 'PoliciaNac', 'Bomberos', 'AutobusesU',
       'Bocas de m', 'Farmacias', 'Hospitales', 'CentrosSal', 'CentrosEns',
       'ColegiosPu','CODDISTRIT', 'CODBARRIO']).set_index("id")

In [7]:
df.head()

,sq_mt_built,n_rooms,n_bathrooms,floor,buy_price,buy_price_by_area,is_renewal_needed,is_new_development,has_lift,is_exterior,has_parking,lat,long,security,transport,health,education
id,,,,,,,,,,,,,,,,,
21742,64,2,1,3,85000,1328,0,0,0,1,0,"40,342876","-3,688974",0,20,6,3
21741,70,3,1,4,129900,1856,1,0,1,1,0,"40,357024","-3,697098",1,94,18,4
21740,94,2,2,1,144247,1535,0,0,1,1,0,"40,344622","-3,715213",2,127,22,7
21739,64,2,1,0,109900,1717,0,0,1,1,0,"40,343787","-3,70866",2,127,22,7
21738,108,2,2,4,260000,2407,0,0,1,1,1,"40,355564","-3,687558",0,101,16,7

In [45]:
df.to_csv("outputs/clean_data_w_neigh.csv")